### ISSUE TITLE
请问一下，可以指定图片本地缓存路径，并且在加载时自动下载到缓存路径么

### ISSUE THREAD

**Issue by Longtianmu** [ltttttttttttt/load-the-image#1]

**Comment by ltttttttttttt** [comment]
可以的,默认就有本地文件缓存,路径为:此电脑->图片->LoadTheImageCache
如果要修改的话,可以使用如下代码: 
`LoadTheImageManager.fileCache = ImageFileCache(File("C://test_dir"))`

可以在desktop目录的Main.kt的15行左右加这个配置,过两天我会写一个api比较全的中文文档
