### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Xiaolangs** [ltttttttttttt/load-the-image#2]
Exception in thread "main" java.lang.NoClassDefFoundError: kotlinx/coroutines/swing/SwingDispatcherKt
引入 org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.6.2 解决上面报错
引入org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.6.2后以下报错
java.lang.NoSuchMethodError: 'void org.jetbrains.skia.paragraph.ParagraphStyle.setTextIndent(org.jetbrains.skia.paragraph.TextIndent)

使用版本
kotlin("jvm") version "1.6.10"
 id("org.jetbrains.compose") version "1.1.0"

环境 jdk17 desktop

**Comment by ltttttttttttt** [comment]
我瞅瞅

**Comment by ltttttttttttt** [comment]
> 异常 in thread “main” java.lang.NoClassDefFoundError： kotlinx/coroutines/swing/SwingDispatcherKt 引入 org.jetbrains.kotlinx：kotlinx-coroutines-swing：1.6.2 解决上面报错 引入org.jetbrains.kotlinx：kotlinx-coroutines-swing：1.6.2后以下报错 java.lang.NoSuchMethodError： 'void org.jetbrains.skia.paragraph.ParagraphStyle.setTextIndent（org.jetbrains.skia.paragraph.TextIndent）
> 
> 使用版本 kotlin（“jvm”） version “1.6.10” id（“org.jetbrains.compose”） version “1.1.0”
> 
> 环境 jdk17 desktop

我这边试了下没有问题,你这个报错应该是别的代码引起的,还有一点,我没有用kotlin('jvm"),而是使用的 
    kotlin("multiplatform") version "1.6.10"

**Comment by Xiaolangs** [comment]
那你是jvm的 我目前就用了 okhttp一个库  没有接入的时候正常的 接入以后才有上面哪些错误

**Comment by ltttttttttttt** [comment]
> 那你是jvm的 我目前就用了 okhttp一个库 没有接入的时候正常的 接入以后才有上面哪些错误

要不然你把你的build.gradle内容发过来，我看能复现不能

**Comment by Xiaolangs** [comment]
我在公司电脑弄的。就是新建的项目 单desktop的

**Comment by ltttttttttttt** [comment]
> 我在公司电脑弄的。就是新建的项目 单desktop的

破案了emmm,看了下compose-jb的注释,这个应该是它的bug,把comopse版本提升到1.1.1就不报错了,
而且也没有NoClassDefFoundError: kotlinx/coroutines/swing/SwingDispatcherKt报错了
如果不需要使用Dispatchers.Main可以不添加org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.6.2依赖
你试下还有问题没了

**Comment by Xiaolangs** [comment]
好的 麻烦了。我周一看看。

**Comment by ltttttttttttt** [comment]
> 好的 麻烦了。我周一看看。

问题解决了吗?不报错我就关了哈
