### ISSUE TITLE
更多平台支持

### ISSUE THREAD

**Issue by Matcha-xiaobin** [ltttttttttttt/load-the-image#5]
有没有考虑过增加ios支持，或者目前有支持ios的吗？
心血来潮来学下compose_jb，结果发现通用的图片加载库都没得，太难了

**Comment by ltttttttttttt** [comment]
我这个库只打算支持desktop,没有精力所以后续不会支持全平台
可以使用这个(我ios上也用的这个):  https://github.com/qdsfdhvh/compose-imageloader
据说coil3也会支持KMP(不过有的等)

**Comment by ltttttttttttt** [comment]
这里我有篇文章介绍了一些KMP架构有关的你可以看看
https://blog.csdn.net/qq_33505109/article/details/134696748

**Comment by Matcha-xiaobin** [comment]
感谢！
